name: elo-ranking
channels:
  - defaults
dependencies:
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - openssl=1.1.1g=he774522_1
  - pip=20.2.2=py38_0
  - python=3.8.5=he1778fa_0
  - setuptools=49.6.0=py38_0
  - sqlite=3.33.0=h2a8f88b_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - numpy==1.19.1
    - pandas==1.1.1
    - python-dateutil==2.8.1
    - pytz==2020.1

